(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const archive=Array.from({length:11},(_,i)=>({src:`assets/film/archive/material-${String(i+1).padStart(2,'0')}.jpg`,code:`MAT_${String(i+1).padStart(3,'0')}`,type:[0,3,4,6,10].includes(i)?'POSTER':'STILL'}));
  let archiveIndex=0;
  const image=$('#archiveImage'), code=$('#archiveCode'), count=$('#archiveCount'), dots=$('#archiveDots'), drawerGrid=$('#drawerGrid');
  function buildDots(root, cls='active'){ if(!root)return; root.innerHTML=archive.map((_,i)=>`<i class="${i===archiveIndex?cls:''}"></i>`).join(''); }
  function renderArchive(){ const item=archive[archiveIndex]; if(image){image.src=item.src; image.alt=`${item.code} / ${item.type}`;} if(code)code.textContent=`${item.code} // ${item.type}`; if(count)count.textContent=`${String(archiveIndex+1).padStart(2,'0')} / ${archive.length}`; buildDots(dots); buildDots($('#lightboxDots')); const lb=$('#lightboxImage'),lbc=$('#lightboxCode'),lbn=$('#lightboxCount'); if(lb)lb.src=item.src;if(lbc)lbc.textContent=`${item.code} // ${item.type}`;if(lbn)lbn.textContent=`${String(archiveIndex+1).padStart(2,'0')} / ${archive.length}`; $$('.drawer-grid button').forEach((b,i)=>b.classList.toggle('active',i===archiveIndex)); }
  if(drawerGrid){drawerGrid.innerHTML=archive.map((x,i)=>`<button type="button" data-index="${i}"><img src="${x.src}" loading="lazy" alt="${x.code}"><span>${x.code} // ${x.type}</span></button>`).join(''); drawerGrid.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;archiveIndex=+b.dataset.index;renderArchive();});}
  $('#archivePrev')?.addEventListener('click',()=>{archiveIndex=(archiveIndex-1+archive.length)%archive.length;renderArchive();});
  $('#archiveNext')?.addEventListener('click',()=>{archiveIndex=(archiveIndex+1)%archive.length;renderArchive();});
  const wall=$('#archiveWall'), drawer=$('#archiveDrawer'), toggle=$('#drawerToggle');
  function setDrawer(open){if(!wall)return;wall.classList.toggle('open',open);drawer?.setAttribute('aria-hidden',String(!open));toggle?.setAttribute('aria-expanded',String(open));}
  toggle?.addEventListener('click',()=>setDrawer(!wall.classList.contains('open'))); $('#drawerClose')?.addEventListener('click',()=>setDrawer(false));
  const lb=$('#lightbox'); function setLightbox(open){if(!lb)return;lb.classList.toggle('open',open);lb.setAttribute('aria-hidden',String(!open));document.body.style.overflow=open?'hidden':''; if(open)renderArchive();}
  $('#openLightbox')?.addEventListener('click',()=>setLightbox(true)); $('#archivePicture')?.addEventListener('click',()=>setLightbox(true)); $('#lightboxClose')?.addEventListener('click',()=>setLightbox(false));
  $('#lightboxPrev')?.addEventListener('click',()=>{archiveIndex=(archiveIndex-1+archive.length)%archive.length;renderArchive();}); $('#lightboxNext')?.addEventListener('click',()=>{archiveIndex=(archiveIndex+1)%archive.length;renderArchive();});
  lb?.addEventListener('click',e=>{if(e.target===lb)setLightbox(false)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){setLightbox(false);setDrawer(false)} if(lb?.classList.contains('open')&&e.key==='ArrowLeft'){$('#lightboxPrev')?.click()} if(lb?.classList.contains('open')&&e.key==='ArrowRight'){$('#lightboxNext')?.click()}});
  renderArchive();

  const subjects=[
    {id:'01',role:'Гор',name:'Арман О.',status:'CAST CONFIRMED',record:'PUBLIC/01'},
    {id:'02',role:'Антагонист',name:'Богдан В.',status:'CAST CONFIRMED',record:'PUBLIC/02'},
    {id:'03',role:'Марк',name:'Левон',status:'CAST CONFIRMED',record:'PUBLIC/03'},
    {id:'04',role:'Ведущая',name:'Юля Ш.',status:'CAST CONFIRMED',record:'PUBLIC/04'},
    {id:'05',role:'Музыкант',name:'Арсен О.',status:'CAST CONFIRMED',record:'PUBLIC/05'},
    {id:'06',role:'Дедушка Гора',name:'Александр К.',status:'CAST CONFIRMED',record:'PUBLIC/06'},
    {id:'07',role:'Детектив',name:'Белла А.',status:'CAST CONFIRMED',record:'PUBLIC/07'}];
  const subjectList=$('#subjectList');
  if(subjectList){subjectList.innerHTML=subjects.map((s,i)=>`<button class="subject-row" data-index="${i}"><span>SUBJECT_${s.id}</span><strong>${s.role}</strong><i>+</i></button>`).join(''); subjectList.addEventListener('click',e=>{const b=e.target.closest('.subject-row'); if(!b)return; showSubject(+b.dataset.index);});}
  function resetSubject(){ $$('.subject-row').forEach(b=>b.classList.remove('active')); const c=$('#subjectContent'); if(c)c.innerHTML='<span class="subject-code">SUBJECT // UNIDENTIFIED</span><h3>???</h3><p>???</p>'; if($('#fieldRole'))$('#fieldRole').textContent='???';if($('#fieldStatus'))$('#fieldStatus').textContent='???';if($('#fieldRecord'))$('#fieldRecord').textContent='—';}
  function showSubject(i){const s=subjects[i]; $$('.subject-row').forEach((b,n)=>b.classList.toggle('active',n===i)); const c=$('#subjectContent'); if(c){c.animate([{opacity:.15,transform:'translateY(-5px)'},{opacity:1,transform:'translateY(0)'}],{duration:260,easing:'ease-out'});c.innerHTML=`<span class="subject-code">SUBJECT_${s.id} // IDENTIFIED</span><h3>${s.name}</h3><p>${s.role}</p>`;} $('#fieldRole').textContent=s.role;$('#fieldStatus').textContent=s.status;$('#fieldRecord').textContent=s.record;}
  $('#subjectReset')?.addEventListener('click',resetSubject); resetSubject();

  const faq=[
    ['Когда выйдет фильм?','Точная дата релиза будет объявлена, когда система завершит разработку. Подтверждённая дата появится на этом сайте.','ОЖИДАНИЕ ПОДТВЕРЖДЕНИЯ','НЕПОДТВЕРЖДЁННЫЕ ДАТЫ НЕ ПУБЛИКУЮТСЯ'],
    ['Где можно будет посмотреть фильм?','Площадки появятся в разделе «Где посмотреть» после подтверждения релиза.','ОЖИДАНИЕ РЕЛИЗА','СПИСОК ПЛОЩАДОК ПУБЛИКУЕТСЯ ПОСЛЕ ПОДТВЕРЖДЕНИЯ'],
    ['Будет ли показ в кинотеатрах?','Требуется уточнение.','ТРЕБУЕТСЯ УТОЧНЕНИЕ','КАНАЛЫ ПОКАЗА УТОЧНЯЮТСЯ'],
    ['Как связаться с создателями?','Официальный публичный контакт автора находится в разделе «Контакты».','ПУБЛИЧНЫЙ КАНАЛ ОТКРЫТ','ИСПОЛЬЗУЙТЕ РАЗДЕЛ «КОНТАКТЫ»'],
    ['Что за история у Хищения?','История разворачивается в 2045 году в системе, где человек должен доказать обществу свою пользу. Подробнее — в разделе «О фильме».','ДОСЬЕ ОТКРЫТО','БАЗОВАЯ ИНФОРМАЦИЯ ДОСТУПНА В РАЗДЕЛЕ «О ФИЛЬМЕ»'],
    ['Когда появятся новые материалы?','Новые материалы публикуются после подтверждения автора и подготовки к публикации.','ОЖИДАНИЕ ОБНОВЛЕНИЯ','НОВЫЕ МАТЕРИАЛЫ ПУБЛИКУЮТСЯ ПОСЛЕ ПОДТВЕРЖДЕНИЯ'],
    ['Кто работает над фильмом?','Подтверждённые имена режиссёра и актёров публикуются на этом сайте. Состав может дополняться по мере подтверждения материалов.','ПОДТВЕРЖДЁННЫЕ ДАННЫЕ','СОСТАВ ОБНОВЛЯЕТСЯ ПО МЕРЕ ПОДТВЕРЖДЕНИЯ'],
    ['На сайте есть безопасность?','Система позволяет пользователям использовать технический идентификатор без привязки личных данных для работы профиля и отзывов.','ПРОТОКОЛ АКТИВЕН','МИНИМУМ ДАННЫХ // ЛОКАЛЬНАЯ ПРИВЯЗКА ПРОФИЛЯ']];
  const faqList=$('#faqList'); if(faqList){faqList.innerHTML=faq.map((q,i)=>`<button class="faq-row" data-index="${i}"><span>QUERY_${String(i+1).padStart(2,'0')}</span><strong>${q[0]}</strong><i>+</i></button>`).join('');faqList.addEventListener('click',e=>{const b=e.target.closest('.faq-row');if(!b)return;showFaq(+b.dataset.index);});}
  function showFaq(i){const q=faq[i];$$('.faq-row').forEach((b,n)=>b.classList.toggle('active',n===i));const a=$('#faqAnswer');if(a){a.animate([{opacity:.15,transform:'translateY(-4px)'},{opacity:1,transform:'translateY(0)'}],{duration:240,easing:'ease-out'});a.innerHTML=`<span>QUERY_${String(i+1).padStart(2,'0')} // VERIFIED RESPONSE</span><h3>${q[0]}</h3><p>${q[1]}</p>`;}$('#faqStatus').textContent=q[2];$('#faqMessage').textContent=q[3];$('#faqLog').textContent=`SYSTEM LOG // Q${String(i+1).padStart(2,'0')}.RSP`;}

  const sections=$$('.section-screen'); const fill=$('#progressFill'), pc=$('#progressCode'); function scrollProgress(){const max=document.documentElement.scrollHeight-innerHeight;const p=max>0?scrollY/max:0;if(fill)fill.style.height=`${p*100}%`;let current=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<innerHeight*.48)current=s});if(current&&pc)pc.textContent=`${current.dataset.index} / ${current.dataset.code}`;} addEventListener('scroll',scrollProgress,{passive:true});scrollProgress();

  const translations={en:{systemActive:'SYSTEM ACTIVE',publicAccess:'PUBLIC ACCESS',filmDevelopment:'FILM IN DEVELOPMENT · 2045',navAbout:'ABOUT',navMaterials:'MATERIALS',navTrailer:'TRAILER',navWatch:'WHERE TO WATCH',navCast:'CAST',navReviews:'REVIEWS',navContacts:'CONTACTS',heroLead:'In a world where a person must prove their usefulness to the system, growing up becomes a fight for the right to choose one’s own future.',watchTrailer:'WATCH TRAILER',aboutFilm:'ABOUT THE FILM',aboutTitle:'Year 2045.',aboutP1:'Earth’s population has exceeded the acceptable limit. The state creates a new system in which every person must prove their usefulness to society.',aboutP2:'Children are placed under special control from an early age and assigned to designated sections.',aboutP3:'Gor lives with his 75-year-old grandfather and tries to adapt to the new world. The story follows Gor’s coming of age, his friendship with Mark and the fight for his own future in a system where human life is gradually becoming a resource.',labelTitle:'TITLE',labelGenre:'GENRE',labelDirector:'DIRECTOR',labelStatus:'STATUS',genre:'Dystopia · Drama · Action · Adventure · Science Fiction',inDevelopment:'In development',materialsTitle:'Visual materials',materialsLead:'Materials are presented in the author’s original form. Text inside posters may remain in Russian.',trailerTitle:'Trailer',trailerNote:'The original trailer audio is in Russian. English subtitles may be added after approval by the author.',watchTitle:'Where to watch',watchLead:'Platforms will appear here after the release is confirmed. For now, this section works as a public access point to the project.',soon:'coming soon',castTitle:'Cast',reviewsTitle:'Viewer reviews',reviewsLead:'Viewer ratings form the film’s “Freshness”. Scores from 7–10 are considered positive.',notEnough:'NOT ENOUGH RATINGS',averageScore:'AVERAGE SCORE',ratings:'ratings',openReviews:'OPEN REVIEWS',faqTitle:'Frequently asked questions',selectQuestion:'Select a question // awaiting response',contactsTitle:'Contacts',contactsLead:'The film author’s official public channel.'},ru:{}};
  const langBtn=$('#langToggle');let lang='ru';langBtn?.addEventListener('click',()=>{lang=lang==='ru'?'en':'ru';langBtn.textContent=lang==='ru'?'EN':'RU';$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(lang==='en'&&translations.en[k]){if(!el.dataset.ru)el.dataset.ru=el.textContent;el.textContent=translations.en[k]}else if(lang==='ru'&&el.dataset.ru){el.textContent=el.dataset.ru}});document.documentElement.lang=lang;});
})();
